id: AB1111111
title: 'The Precious Jewel Essence: A Prayer of the Four Dharmas'
type: translation
pechas:
- IF17F81EF
- ID4C3774D
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:38:44.173327
  last_modified_at: 2023-01-04 11:38:44.173334
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IF17F81EF/4B57: 9B09
  ID4C3774D/BB30: 9B09
